Repository kata-containers/documentation, pull requests merged in 2018-05, with the labels that each got.

#61 docs: Add ubuntu installation guide
  install/ubuntu-installation-guide.md
Labels: review

#65 add initial kata architecture docs
  arch-images/CNI_diagram.png
  arch-images/CNM_detailed_diagram.png
  arch-images/CNM_overall_diagram.png
  arch-images/DAX.png
  arch-images/docker-kata.png
  arch-images/kata-crio-uml.png
  arch-images/kata-crio-uml.txt
  arch-images/kata-oci-create.svg
  arch-images/kata-oci-create.txt
  arch-images/kata-oci-exec.svg
  arch-images/kata-oci-exec.txt
  arch-images/kata-oci-start.svg
  arch-images/kata-oci-start.txt
  arch-images/network.png
  arch-images/qemu.png
  architecture.md
Labels: review

#66 developer-guide: update guest kernel image section
  Developer-Guide.md
Labels: review

#79 docs: Add upgrading doc
  Upgrading.md
Labels: release-gating

#20 Add POC documentation of Kata working with OpenStack Zun
  kata-zun1.png
  kata-zun2.png
  kata-zun3.png
  kata-zun4.png
  kata-zun5.png
  zun_kata.md
Labels: in progress, use-case-documentation
